id: ny_traffic_events_pipeline
namespace: de-zc-finalproject

variables:
  welcome_message: "Welcome to the NY Traffic Events Pipeline!"
  format: "json"
  

tasks:
  - id: log_welcome
    type: io.kestra.plugin.core.log.Log
    message: "{{ vars.welcome_message }}"

  - id: extract_real_time_events
    type: io.kestra.plugin.scripts.Python.Script
    containerImage: python:3.12-slim
    inputFiles:

  - id: sleep
    type: io.kestra.plugin.core.flow.Sleep
    duration: PT10S
  
  - id: log_goodbye
    type: io.kestra.plugin.core.log.Log
    message: "Goodbye from the NY Traffic Events Pipeline!"


pluginDefaults:
  - type: io.kestra.plugin.core.log.Log
    values:
      level: INFO

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/10 * * * *"
    disabled: true
